name: uang_saku
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^0.6.0
  date_field: ^1.0.4
  date_range_picker: ^1.0.3
  dotted_border: ^1.0.7
  flutter_chips_input: ^1.9.5
  percent_indicator: ^2.1.9+1
  image_picker: ^0.6.7+22
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  fading_edge_scrollview: ^1.1.4
  google_fonts: ^1.1.2
  http: ^0.12.0+4
  pin_code_fields: null
  shared_preferences: ^0.5.7
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  email_validator: ^1.0.6
  badges: ^1.2.0
  firebase_messaging: ^7.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/man.png
    - images/woman.png
    - images/otp.png
    - images/resetpass.png
    - images/uangsaku.png
    - images/icon_dashboard.png
    - images/kasbon.png
    - images/reimburse.png
    - images/jumlah_approval.png
    - images/create.gif
    - images/Direktur.png
    - images/Supervisor.png
    - images/Korcab.png
    - images/Keuangan.png
    - images/icon-approve-white.png
    - images/icon-approve.png
    - images/icon-coin.png
    - images/icon-decline-white.png
    - images/icon-decline.png
    - images/icon-dollar-white.png
    - images/icon-done.png
    - images/icon-download.png
    - images/icon-send.png
    - images/paper-bill.png
    - images/paper-clip.png
    - images/paper-done.png
    - images/send-file-blue.png
    - images/send-file-cyan.png
    - images/send-file-dark-blue.png
    - images/send-file-decline.png
    - images/send-file-download.png
    - images/send-file-money.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
    #         style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
